#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

usage() {
  cat <<'USAGE'
Usage:
  scripts/codex-pr-creator.sh inspect
  scripts/codex-pr-creator.sh create "PR title" PR_BODY_FILE [COMMIT_MESSAGE] [--draft]
  scripts/codex-pr-creator.sh create-auto "PR title" [COMMIT_MESSAGE] [--draft]

Environment fallback for create:
  PR_TITLE
  PR_BODY_FILE
  COMMIT_MESSAGE
  DRAFT=1
USAGE
}

current_branch() {
  git branch --show-current
}

inspect() {
  local branch
  branch="$(current_branch)"

  printf '== PR Creator Inspect ==\n'
  printf 'branch: %s\n\n' "$branch"

  printf '== Status ==\n'
  git status --short --branch

  printf '\n== Diff Stat ==\n'
  git diff --stat || true

  printf '\n== Commits ahead of main ==\n'
  git log --oneline main..HEAD || true

  printf '\n== Existing PRs for branch ==\n'
  gh pr list --head "$branch" --json number,title,url,state,isDraft
}

is_draft_arg() {
  for arg in "$@"; do
    if [ "$arg" = "--draft" ]; then
      return 0
    fi
  done
  return 1
}

commit_if_needed() {
  local commit_message="$1"

  if [ -n "$commit_message" ] && [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "$commit_message"
  fi

  if [ -n "$(git status --porcelain)" ]; then
    printf '[STOP] Worktree has uncommitted changes. Set COMMIT_MESSAGE or commit manually.\n' >&2
    exit 2
  fi
}

generate_body_file() {
  local title="$1"
  local body_file
  body_file="$(mktemp)"

  {
    printf '## Summary\n\n'
    printf '- %s\n\n' "$title"
    printf '## Changes\n\n'
    git diff --stat main..HEAD | sed 's/^/- /'
    printf '\n## Commits\n\n'
    git log --oneline main..HEAD | sed 's/^/- /'
    printf '\n## Validation\n\n'
    printf '- [ ] `bash scripts/codex-preflight.sh`\n\n'
    printf '## Review Notes\n\n'
    printf '- PR body was generated by `scripts/codex-pr-creator.sh create-auto`.\n'
  } > "$body_file"

  printf '%s\n' "$body_file"
}

push_and_create_or_show_pr() {
  local branch="$1"
  local title="$2"
  local body_file="$3"
  local draft="$4"

  git push -u origin "$branch"

  if gh pr list --head "$branch" --json number --jq 'length' | grep -qx '0'; then
    args=(--base main --head "$branch" --title "$title" --body-file "$body_file")
    if [ "$draft" = "1" ]; then
      args+=(--draft)
    fi
    gh pr create "${args[@]}"
  else
    printf 'Existing PR found for %s:\n' "$branch"
    gh pr list --head "$branch" --json number,title,url,state,isDraft
  fi
}

create() {
  local branch
  branch="$(current_branch)"
  local title="${PR_TITLE:-${1:-}}"
  local body_file="${PR_BODY_FILE:-${2:-}}"
  local commit_message="${COMMIT_MESSAGE:-${3:-}}"
  local draft="${DRAFT:-0}"

  if is_draft_arg "$@"; then
    draft=1
  fi

  if [ "$branch" = "main" ]; then
    printf '[STOP] Refusing to create a PR directly from main.\n' >&2
    exit 2
  fi

  commit_if_needed "$commit_message"

  if [ -z "$title" ] || [ -z "$body_file" ]; then
    usage >&2
    exit 2
  fi

  push_and_create_or_show_pr "$branch" "$title" "$body_file" "$draft"
}

create_auto() {
  local branch
  branch="$(current_branch)"
  local title="${PR_TITLE:-${1:-}}"
  local commit_message="${COMMIT_MESSAGE:-${2:-}}"
  local draft="${DRAFT:-0}"
  local body_file

  if is_draft_arg "$@"; then
    draft=1
  fi

  if [ "$branch" = "main" ]; then
    printf '[STOP] Refusing to create a PR directly from main.\n' >&2
    exit 2
  fi

  if [ -z "$title" ]; then
    usage >&2
    exit 2
  fi

  commit_if_needed "$commit_message"

  body_file="$(generate_body_file "$title")"
  trap 'rm -f "$body_file"' EXIT
  push_and_create_or_show_pr "$branch" "$title" "$body_file" "$draft"
}

case "${1:-}" in
  inspect) inspect ;;
  create) shift; create "$@" ;;
  create-auto) shift; create_auto "$@" ;;
  -h|--help|help) usage ;;
  *) usage >&2; exit 2 ;;
esac
