#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

usage() {
  cat <<'USAGE'
Usage:
  scripts/codex-pr-creator.sh inspect
  scripts/codex-pr-creator.sh create "PR title" PR_BODY_FILE [COMMIT_MESSAGE] [--draft]
  scripts/codex-pr-creator.sh create-auto "PR title" [COMMIT_MESSAGE] [--draft]
  scripts/codex-pr-creator.sh create-auto --topic TOPIC --title "PR title" --commit-message "message" [--draft]

Environment fallback for create:
  PR_TITLE
  PR_BODY_FILE
  COMMIT_MESSAGE
  PR_TOPIC
  DRAFT=1
USAGE
}

current_branch() {
  git branch --show-current
}

inspect() {
  local branch
  branch="$(current_branch)"

  printf '== PR Creator Inspect ==\n'
  printf 'branch: %s\n\n' "$branch"

  printf '== Status ==\n'
  git status --short --branch

  printf '\n== Diff Stat ==\n'
  git diff --stat || true

  printf '\n== Commits ahead of origin/main ==\n'
  git log --oneline origin/main..HEAD || true

  printf '\n== Existing PRs for branch ==\n'
  gh pr list --head "$branch" --state all --json number,title,url,state,isDraft
}

is_draft_arg() {
  for arg in "$@"; do
    if [ "$arg" = "--draft" ]; then
      return 0
    fi
  done
  return 1
}

sanitize_topic() {
  local topic="$1"
  topic="$(printf '%s' "$topic" | tr '[:upper:]' '[:lower:]')"
  topic="$(printf '%s' "$topic" | sed -E 's#[^a-z0-9._/-]+#-#g; s#^-+##; s#-+$##')"
  if [ -z "$topic" ]; then
    printf '[STOP] Topic became empty after sanitization.\n' >&2
    exit 2
  fi
  case "$topic" in
    ai/*) printf '%s\n' "$topic" ;;
    *) printf 'ai/%s\n' "$topic" ;;
  esac
}

merged_pr_state_for_branch() {
  local branch="$1"
  gh pr list --head "$branch" --state all --json state --jq '.[0].state // ""'
}

prepare_branch() {
  local topic="$1"
  local current target state ahead_count

  git fetch origin

  current="$(current_branch)"
  if [ -z "$topic" ]; then
    if [ "$current" = "main" ]; then
      printf '[STOP] Current branch is main. Pass --topic so a PR branch can be created.\n' >&2
      exit 2
    fi
    return
  fi

  target="$(sanitize_topic "$topic")"
  if [ "$current" = "$target" ]; then
    return
  fi

  state="$(merged_pr_state_for_branch "$current")"
  ahead_count="$(git rev-list --count origin/main..HEAD)"

  if [ "$current" = "main" ] || [ "$state" = "MERGED" ] || [ "$ahead_count" = "0" ]; then
    if git show-ref --verify --quiet "refs/heads/$target"; then
      git switch "$target"
    else
      git switch -c "$target" origin/main
    fi
    return
  fi

  printf '[STOP] Current branch "%s" has unmerged commits. Switch branches manually or omit --topic.\n' "$current" >&2
  exit 2
}

commit_if_needed() {
  local commit_message="$1"

  if [ -n "$commit_message" ] && [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "$commit_message"
  fi

  if [ -n "$(git status --porcelain)" ]; then
    printf '[STOP] Worktree has uncommitted changes. Set COMMIT_MESSAGE or commit manually.\n' >&2
    exit 2
  fi
}

generate_body_file() {
  local title="$1"
  local body_file
  body_file="$(mktemp)"

  {
    printf '## Summary\n\n'
    printf -- '- %s\n\n' "$title"
    printf '## Changes\n\n'
    git diff --stat origin/main..HEAD | sed 's/^/- /'
    printf '\n## Commits\n\n'
    git log --oneline origin/main..HEAD | sed 's/^/- /'
    printf '\n## Validation\n\n'
    printf -- '- [ ] `bash scripts/codex-preflight.sh`\n\n'
    printf '## Review Notes\n\n'
    printf -- '- PR body was generated by `scripts/codex-pr-creator.sh create-auto`.\n'
  } > "$body_file"

  printf '%s\n' "$body_file"
}

push_and_create_or_show_pr() {
  local branch="$1"
  local title="$2"
  local body_file="$3"
  local draft="$4"

  git push -u origin "$branch"

  if gh pr list --head "$branch" --json number --jq 'length' | grep -qx '0'; then
    args=(--base main --head "$branch" --title "$title" --body-file "$body_file")
    if [ "$draft" = "1" ]; then
      args+=(--draft)
    fi
    gh pr create "${args[@]}"
  else
    printf 'Existing PR found for %s:\n' "$branch"
    gh pr list --head "$branch" --json number,title,url,state,isDraft
  fi
}

create() {
  local branch
  branch="$(current_branch)"
  local title="${PR_TITLE:-${1:-}}"
  local body_file="${PR_BODY_FILE:-${2:-}}"
  local commit_message="${COMMIT_MESSAGE:-${3:-}}"
  local draft="${DRAFT:-0}"

  if is_draft_arg "$@"; then
    draft=1
  fi

  if [ "$branch" = "main" ]; then
    printf '[STOP] Refusing to create a PR directly from main.\n' >&2
    exit 2
  fi

  commit_if_needed "$commit_message"

  if [ -z "$title" ] || [ -z "$body_file" ]; then
    usage >&2
    exit 2
  fi

  push_and_create_or_show_pr "$branch" "$title" "$body_file" "$draft"
}

create_auto() {
  local title="${PR_TITLE:-}"
  local commit_message="${COMMIT_MESSAGE:-}"
  local topic="${PR_TOPIC:-}"
  local draft="${DRAFT:-0}"
  local body_file

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --topic)
        topic="${2:-}"
        shift 2
        ;;
      --title)
        title="${2:-}"
        shift 2
        ;;
      --commit-message)
        commit_message="${2:-}"
        shift 2
        ;;
      --draft)
        draft=1
        shift
        ;;
      --)
        shift
        break
        ;;
      -*)
        printf '[STOP] Unknown option: %s\n' "$1" >&2
        exit 2
        ;;
      *)
        if [ -z "$title" ]; then
          title="$1"
        elif [ -z "$commit_message" ]; then
          commit_message="$1"
        else
          printf '[STOP] Unexpected argument: %s\n' "$1" >&2
          exit 2
        fi
        shift
        ;;
    esac
  done

  prepare_branch "$topic"

  if [ -z "$title" ]; then
    usage >&2
    exit 2
  fi

  commit_if_needed "$commit_message"

  body_file="$(generate_body_file "$title")"
  trap "rm -f '$body_file'" EXIT
  push_and_create_or_show_pr "$(current_branch)" "$title" "$body_file" "$draft"
}

case "${1:-}" in
  inspect) inspect ;;
  create) shift; create "$@" ;;
  create-auto) shift; create_auto "$@" ;;
  -h|--help|help) usage ;;
  *) usage >&2; exit 2 ;;
esac
